### ISSUE TITLE
program crash on certain input

### ISSUE THREAD

**Issue by chrishiestand** [kistek/boss-internal-testing#2]
blah blah3

**Comment by chrishiestand** [comment]
<a href="https://www.boss.local:3000/bounty/boss/tdo0oohepxsgz2le6nv2z4"><img src="https://img.shields.io/endpoint.svg?url=https://api.boss.local:31883/badge/bounty/bounty%3Fgid%3Dboss%2Ftdo0oohepxsgz2le6nv2z4" /></a>

**Comment by chrishiestand** [comment]
<a href="https://www.boss.local:3000/bounty/boss/k93u83nm9vi1fgz0cnihdi"><img src="https://img.shields.io/endpoint.svg?url=https://7e39f08d.ngrok.io/badge/bounty/bounty%3Fgid%3Dboss%2Fk93u83nm9vi1fgz0cnihdi" /></a>

**Comment by dasRoss** [comment]
blah
